// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc/proto/application/application.proto

// +kubebuilder:object:generate=true

package application

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	namespace "github.com/keikoproj/manager/pkg/grpc/proto/namespace"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Application struct {
	//Application Name
	// +kubebuilder:validation:MinLength=1
	//Leave 5 characters to the env since namespace will be constructed using ${appName}-${env}
	// +kubebuilder:validation:MaxLength=59
	// +kubebuilder:validation:Pattern=^[a-z0-9-]+$
	// +kubebuilder:validation:Required
	// +required
	AppName string `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	//appParams can be used to pass the values to the underlying template being used
	//If included, it tries to replace it in the template mentioned with exported fields
	//If the same entry is provided in namespace params too then it will be overwritten by namespace param value
	// +optional
	AppParams map[string]string `protobuf:"bytes,2,rep,name=appParams,proto3" json:"appParams,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//List of environments to be created for this application
	// +kubebuilder:validation:MinItems=1
	Environments         []*Environment `protobuf:"bytes,11,rep,name=environments,proto3" json:"environments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_4532862135811ae9, []int{0}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *Application) GetAppParams() map[string]string {
	if m != nil {
		return m.AppParams
	}
	return nil
}

func (m *Application) GetEnvironments() []*Environment {
	if m != nil {
		return m.Environments
	}
	return nil
}

type Environment struct {
	//Application environment
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Pattern=^[a-z0-9-]+$
	// +required
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//Each environment must have one namespace
	// +required
	Namespace            *namespace.Namespace `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_4532862135811ae9, []int{1}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Environment) GetNamespace() *namespace.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func init() {
	proto.RegisterType((*Application)(nil), "application.Application")
	proto.RegisterMapType((map[string]string)(nil), "application.Application.AppParamsEntry")
	proto.RegisterType((*Environment)(nil), "application.Environment")
}

func init() {
	proto.RegisterFile("pkg/grpc/proto/application/application.proto", fileDescriptor_4532862135811ae9)
}

var fileDescriptor_4532862135811ae9 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0xab, 0x95, 0xcc, 0x8a, 0xc8, 0xd2, 0xc3, 0xd2, 0x53, 0xe8, 0xc5, 0x1c, 0x24,
	0x0b, 0xf1, 0xe0, 0x1f, 0x7a, 0xa9, 0x90, 0x6b, 0x91, 0x80, 0x17, 0x6f, 0xd3, 0xb0, 0xc4, 0x98,
	0xee, 0xee, 0xb0, 0x49, 0x0b, 0xfd, 0xca, 0x7e, 0x0a, 0x31, 0xb1, 0x6e, 0x22, 0x78, 0xfb, 0xcd,
	0xcb, 0x7b, 0x8f, 0xc9, 0x2c, 0xdc, 0x52, 0x5d, 0xca, 0xd2, 0x51, 0x21, 0xc9, 0xd9, 0xd6, 0x4a,
	0x24, 0xda, 0x55, 0x05, 0xb6, 0x95, 0x35, 0x43, 0x4e, 0xba, 0xaf, 0x9c, 0x0d, 0xa4, 0x45, 0xfc,
	0x27, 0x6a, 0x50, 0xab, 0x86, 0xb0, 0x50, 0x9e, 0xfa, 0xd8, 0xf2, 0x33, 0x00, 0xb6, 0xf6, 0x49,
	0x2e, 0xe0, 0x02, 0x89, 0x36, 0xa8, 0x95, 0x08, 0xa2, 0x20, 0x0e, 0xf3, 0xd3, 0xc8, 0x33, 0x08,
	0x91, 0xe8, 0x05, 0x1d, 0xea, 0x46, 0x4c, 0xa2, 0x69, 0xcc, 0xd2, 0x9b, 0x64, 0xb8, 0xc7, 0x7a,
	0xcc, 0xbd, 0x33, 0x33, 0xad, 0x3b, 0xe6, 0x3e, 0xc9, 0x57, 0x70, 0xa9, 0xcc, 0xa1, 0x72, 0xd6,
	0x68, 0x65, 0xda, 0x46, 0xb0, 0xae, 0x49, 0x8c, 0x9a, 0x32, 0x6f, 0xc8, 0x47, 0xee, 0xc5, 0x0a,
	0xae, 0xc6, 0xd5, 0xfc, 0x1a, 0xa6, 0xb5, 0x3a, 0xfe, 0x2c, 0xfb, 0x8d, 0x7c, 0x0e, 0xe7, 0x07,
	0xdc, 0xed, 0x95, 0x98, 0x74, 0x5a, 0x3f, 0x3c, 0x4d, 0x1e, 0x82, 0xe5, 0x2b, 0xb0, 0x41, 0x35,
	0xe7, 0x70, 0x66, 0xfc, 0x8f, 0x76, 0xcc, 0x53, 0x08, 0x7f, 0x4f, 0x24, 0x66, 0x51, 0x10, 0xb3,
	0x74, 0x9e, 0xf8, 0xa3, 0x6d, 0x4e, 0x94, 0x7b, 0xdb, 0xf3, 0xe3, 0xdb, 0x7d, 0x59, 0xb5, 0xef,
	0xfb, 0x6d, 0x52, 0x58, 0x2d, 0x6b, 0x55, 0xd5, 0x96, 0x9c, 0xfd, 0x90, 0x1a, 0x0d, 0x96, 0xca,
	0xc9, 0xff, 0xdf, 0x71, 0x3b, 0xeb, 0xa4, 0xbb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0xf5,
	0xed, 0x90, 0xec, 0x01, 0x00, 0x00,
}
