// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc/proto/namespace/template.proto

package namespace

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "k8s.io/api/core/v1"
	v11 "k8s.io/api/rbac/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NamespaceTemplate struct {
	//exportedParamName to be exported from this template
	//These params will be passed in namespace creation and values will be replaced
	//If you are using params in the template, make sure to to include in the resources with ${exportedParamName}
	//+optional
	ExportedParamName []string `protobuf:"bytes,1,rep,name=exportedParamName,proto3" json:"exportedParamName,omitempty"`
	//NamespaceResources consists of all the resources to be created in namespace including custom resources
	//+required
	NsResources          *NamespaceResources `protobuf:"bytes,2,opt,name=nsResources,proto3" json:"nsResources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NamespaceTemplate) Reset()         { *m = NamespaceTemplate{} }
func (m *NamespaceTemplate) String() string { return proto.CompactTextString(m) }
func (*NamespaceTemplate) ProtoMessage()    {}
func (*NamespaceTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f02f0592f6a6cd, []int{0}
}

func (m *NamespaceTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceTemplate.Unmarshal(m, b)
}
func (m *NamespaceTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceTemplate.Marshal(b, m, deterministic)
}
func (m *NamespaceTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceTemplate.Merge(m, src)
}
func (m *NamespaceTemplate) XXX_Size() int {
	return xxx_messageInfo_NamespaceTemplate.Size(m)
}
func (m *NamespaceTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceTemplate proto.InternalMessageInfo

func (m *NamespaceTemplate) GetExportedParamName() []string {
	if m != nil {
		return m.ExportedParamName
	}
	return nil
}

func (m *NamespaceTemplate) GetNsResources() *NamespaceResources {
	if m != nil {
		return m.NsResources
	}
	return nil
}

type NamespaceResources struct {
	//Namespace is mandatory
	// +required
	Namespace *v1.Namespace `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	//Resources to be created and must include at least namespace
	// +optional
	Resources            []*Resource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NamespaceResources) Reset()         { *m = NamespaceResources{} }
func (m *NamespaceResources) String() string { return proto.CompactTextString(m) }
func (*NamespaceResources) ProtoMessage()    {}
func (*NamespaceResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f02f0592f6a6cd, []int{1}
}

func (m *NamespaceResources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceResources.Unmarshal(m, b)
}
func (m *NamespaceResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceResources.Marshal(b, m, deterministic)
}
func (m *NamespaceResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceResources.Merge(m, src)
}
func (m *NamespaceResources) XXX_Size() int {
	return xxx_messageInfo_NamespaceResources.Size(m)
}
func (m *NamespaceResources) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceResources.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceResources proto.InternalMessageInfo

func (m *NamespaceResources) GetNamespace() *v1.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *NamespaceResources) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Resource struct {
	//ServiceAccount to be created for this namespace.
	// Must include type=ServiceAccount and only service account will be read at
	// the server side and everything else will be ignored
	// +optional
	ServiceAccount *v1.ServiceAccount `protobuf:"bytes,1,opt,name=serviceAccount,proto3" json:"serviceAccount,omitempty"`
	//Role to be created for this namespace.
	// Must include type=Role and only Role will be read at
	// the server side and everything else will be ignored
	// +optional
	Role *v11.Role `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	//RoleBinding to bind the role and service account for this namespace.
	// Must include type=RoleBinding and only RoleBinding will be read at
	// the server side and everything else will be ignored
	// +optional
	RoleBinding *v11.RoleBinding `protobuf:"bytes,3,opt,name=roleBinding,proto3" json:"roleBinding,omitempty"`
	//ResourceQuota to be created for this namespace.
	// Must include type=ResourceQuota and only ResourceQuota will be read at
	// the server side and everything else will be ignored.
	// +optional
	ResourceQuota *v1.ResourceQuota `protobuf:"bytes,4,opt,name=resourceQuota,proto3" json:"resourceQuota,omitempty"`
	// +required
	Name string `protobuf:"bytes,15,opt,name=name,proto3" json:"name,omitempty"`
	//Typre represents which k8s resource is being included in the resource entry
	//Allowed values are
	// - ServiceAccount
	// - Role
	// - RoleBinding
	// - ResourceQuota
	// +kubebuilder:validation:Enum=ServiceAccount;Role;RoleBinding;ResourceQuota
	Type string `protobuf:"bytes,16,opt,name=type,proto3" json:"type,omitempty"`
	//dependsOn is an optional field and can be used to delay the creation until the referenced resource got created
	//dependsOn should provide the name of the resource it dependent on
	// +optional
	DependsOn string `protobuf:"bytes,17,opt,name=dependsOn,proto3" json:"dependsOn,omitempty"`
	//createOnly param can be used to control whether resource to be created only once and do not overwrite in subsequent reconcile process
	// +optional
	// +kubebuilder:validation:Enum="true";"false"
	CreateOnly           string   `protobuf:"bytes,18,opt,name=createOnly,proto3" json:"createOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f02f0592f6a6cd, []int{2}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetServiceAccount() *v1.ServiceAccount {
	if m != nil {
		return m.ServiceAccount
	}
	return nil
}

func (m *Resource) GetRole() *v11.Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *Resource) GetRoleBinding() *v11.RoleBinding {
	if m != nil {
		return m.RoleBinding
	}
	return nil
}

func (m *Resource) GetResourceQuota() *v1.ResourceQuota {
	if m != nil {
		return m.ResourceQuota
	}
	return nil
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Resource) GetDependsOn() string {
	if m != nil {
		return m.DependsOn
	}
	return ""
}

func (m *Resource) GetCreateOnly() string {
	if m != nil {
		return m.CreateOnly
	}
	return ""
}

func init() {
	proto.RegisterType((*NamespaceTemplate)(nil), "namespace.NamespaceTemplate")
	proto.RegisterType((*NamespaceResources)(nil), "namespace.NamespaceResources")
	proto.RegisterType((*Resource)(nil), "namespace.Resource")
}

func init() {
	proto.RegisterFile("pkg/grpc/proto/namespace/template.proto", fileDescriptor_32f02f0592f6a6cd)
}

var fileDescriptor_32f02f0592f6a6cd = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4b, 0x8f, 0xd3, 0x30,
	0x14, 0x85, 0x95, 0x69, 0x85, 0xc8, 0x8d, 0x78, 0xd4, 0x6c, 0xac, 0x11, 0x8f, 0x92, 0x0d, 0x59,
	0x8c, 0x62, 0x75, 0xd8, 0x20, 0xb1, 0x40, 0x33, 0x1b, 0x24, 0x16, 0x0c, 0x18, 0x56, 0xec, 0x3c,
	0xce, 0x55, 0x14, 0x4d, 0x6a, 0x5b, 0x8e, 0x5b, 0x31, 0x5b, 0xc4, 0x6f, 0x66, 0x8d, 0xec, 0xe6,
	0xe1, 0x4e, 0xdb, 0x55, 0xad, 0x73, 0xbf, 0x73, 0x7c, 0xae, 0xab, 0xc0, 0x3b, 0x73, 0x57, 0xb3,
	0xda, 0x1a, 0xc9, 0x8c, 0xd5, 0x4e, 0x33, 0x25, 0xd6, 0xd8, 0x19, 0x21, 0x91, 0x39, 0x5c, 0x9b,
	0x56, 0x38, 0x2c, 0xc3, 0x80, 0xa4, 0xe3, 0xe4, 0x3c, 0xbf, 0xfb, 0xd0, 0x95, 0x8d, 0x66, 0xc2,
	0x34, 0x4c, 0x6a, 0x8b, 0x6c, 0xbb, 0x62, 0x35, 0x2a, 0xb4, 0xc2, 0x61, 0xb5, 0xc3, 0xf7, 0x18,
	0x7b, 0x2b, 0xe4, 0x11, 0x26, 0xff, 0x93, 0xc0, 0xe2, 0xeb, 0x90, 0xfa, 0xb3, 0xbf, 0x8e, 0x5c,
	0xc0, 0x02, 0x7f, 0x1b, 0x6d, 0x1d, 0x56, 0xdf, 0x84, 0x15, 0x6b, 0x4f, 0xd0, 0x64, 0x39, 0x2b,
	0x52, 0x7e, 0x38, 0x20, 0x9f, 0x20, 0x53, 0x1d, 0xc7, 0x4e, 0x6f, 0xac, 0xc4, 0x8e, 0x9e, 0x2d,
	0x93, 0x22, 0xbb, 0x7c, 0x55, 0x8e, 0x65, 0xcb, 0xf1, 0x82, 0x11, 0xe2, 0xb1, 0x23, 0xff, 0x9b,
	0x00, 0x39, 0x64, 0xc8, 0x47, 0x98, 0x16, 0xa6, 0x49, 0x9f, 0xba, 0xdb, 0xa9, 0x14, 0xa6, 0x29,
	0xfd, 0xde, 0xe5, 0x76, 0x15, 0xc5, 0x4f, 0x3c, 0x59, 0x41, 0x6a, 0xa3, 0x4a, 0xb3, 0x22, 0xbb,
	0x7c, 0x11, 0x55, 0x1a, 0x6e, 0xe1, 0x13, 0x95, 0xff, 0x3b, 0x83, 0xc7, 0x83, 0x4e, 0xbe, 0xc0,
	0xd3, 0x0e, 0xed, 0xb6, 0x91, 0x78, 0x25, 0xa5, 0xde, 0x28, 0xd7, 0x37, 0xc8, 0x8f, 0x35, 0xf8,
	0xb1, 0x47, 0xf2, 0x07, 0x4e, 0x72, 0x01, 0x73, 0xab, 0x5b, 0xec, 0x5f, 0x86, 0xc6, 0x09, 0xfe,
	0x7f, 0xf1, 0x09, 0x5c, 0xb7, 0xc8, 0x03, 0x45, 0xae, 0x20, 0xf3, 0xbf, 0xd7, 0x8d, 0xaa, 0x1a,
	0x55, 0xd3, 0x59, 0x30, 0xbd, 0x39, 0x65, 0xea, 0x31, 0x1e, 0x7b, 0xc8, 0x67, 0x78, 0x32, 0xac,
	0xf5, 0x7d, 0xa3, 0x9d, 0xa0, 0xf3, 0x10, 0xf2, 0xf6, 0x58, 0x77, 0x1e, 0x83, 0x7c, 0xdf, 0x47,
	0x08, 0xcc, 0xfd, 0x9b, 0xd1, 0x67, 0xcb, 0xa4, 0x48, 0x79, 0x38, 0x7b, 0xcd, 0xdd, 0x1b, 0xa4,
	0xcf, 0x77, 0x9a, 0x3f, 0x93, 0x97, 0x90, 0x56, 0x68, 0x50, 0x55, 0xdd, 0x8d, 0xa2, 0x8b, 0x30,
	0x98, 0x04, 0xf2, 0x1a, 0x40, 0x5a, 0x14, 0x0e, 0x6f, 0x54, 0x7b, 0x4f, 0x49, 0x18, 0x47, 0xca,
	0xf5, 0xf9, 0x2f, 0x7a, 0xea, 0x13, 0xb8, 0x7d, 0x14, 0x84, 0xf7, 0xff, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x60, 0x5b, 0xd1, 0xcb, 0x25, 0x03, 0x00, 0x00,
}
